name: Publish to npm

on:
  pull_request:
    types: [closed]
    branches:
      - master  # Replace with your target release branch if needed

permissions:
  contents: write  # Required to push tags and commits
  id-token: write  # For npm provenance (optional)

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git identity
        run: |
          git config --global user.name "mayur dahake"
          git config --global user.email "mayurdahake13@gmail.com"

      - name: Install dependencies
        run: npm install

      - name: Bump version and generate changelog
        run: npx standard-version

      - name: Push version commit and tags
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push origin HEAD:master --follow-tags

      - name: Build Angular library
        run: npm run build:lib  # Adjust if your script name differs

      - name: Publish to npm
        run: |
          cd npm publish 
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
