name: Publish to npm

on:
  pull_request:
    types: [closed]
    branches:
      - master  # Destination branch to publish from

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'  # 'node' uses the latest stable Node.js
          registry-url: 'https://registry.npmjs.org'

      - name: Set Git user identity
        run: |
          git config --global user.name "mayur dahake"
          git config --global user.email "mayurdahake13@gmail.com"

      - name: Install dependencies
        run: npm install

      - name: Bump version and generate changelog
        run: npx standard-version

      - name: Push version commit and tags
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push --follow-tags origin master

      - name: Build Angular library
        run: npm run build:lib  # Replace with actual build command if different

      - name: Publish to npm
        run: npm publish dist/mdevhub --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
