name: Build and Publish Angular Library

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular library
      run: npx ng build mdevhub --configuration production

    - name: Bump version & generate changelog
      run: |
        npx standard-version
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git push --follow-tags origin main

    - name: Publish to npm
      run: npm publish dist/mdevhub --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
